import io, pathlib, sys

p = pathlib.Path("/Volumes/One Touch/20-research/aura-lab/v2v/chapters/_v3-draft/chapter13-survey-research.qmd")
t = io.open(p, encoding="utf-8").read()
E = [
 ("Restricting to senders with at least five messages leaves **1,195 cases**,",
  "Restricting to senders with at least five messages leaves **6,559 cases**,"),
 ("Those 1,195 rows behave like survey data in every mechanical respect.",
  "Those 6,559 rows behave like survey data in every mechanical respect."),
 ("Work the example through. Of the 1,195 respondents, 91 sent most of their messages in non-gaming channels and 1,104 in gaming channels. That imbalance is a finding about the frame rather than about people: the corpus was drawn from fifty channels weighted toward gaming, so non-gaming chatters are scarce in it by construction. A survey designed to compare those groups would have oversampled non-gaming viewers deliberately. You cannot oversample retroactively, and that constraint is worth feeling, because it is the price of not having designed the collection yourself.",
  "Work the example through. Of the 6,559 respondents, 3,504 sent most of their messages in non-gaming channels and 3,055 in gaming channels. That near-balance is a finding about the frame rather than about people, and it is the frame Chapter 7 describes: the sample takes every non-gaming channel in the population and a matched draw of gaming ones, so the rare group is not rare in the sample. An earlier version of this corpus held five non-gaming channels and produced 91 non-gaming respondents against 1,104 gaming ones, and the comparison below was run on those 91. Every figure in it moved, one of them reversing sign, when the frame was rebuilt. **That is the single most useful thing this chapter can show you about secondary data: the sampling frame is not background information about a study, it is an input to every number the study reports.**"),
 ("Compare the two groups on how often they type in capitals. Non-gaming chatters shout in 9.8 percent of their messages and gaming chatters in 13.9 percent, and the difference clears conventional significance, t(129) = -2.63, with a standardized effect size of d = -0.20. The fractional degrees of freedom are the signature of Welch's (1947) version of the t-test, which does not assume the two groups have equal variances and is the right default when the groups differ this much in size. That second number deserves more attention than the first. An effect of 0.20 is small by any conventional benchmark, which is to say the two groups overlap heavily, and knowing which kind of channel someone favors tells you very little about whether they shout.",
  "Compare the two groups on how often they type in capitals. Non-gaming chatters shout in 21.2 percent of their messages and gaming chatters in 13.4 percent, and the difference clears conventional significance comfortably, t(6555.47) = -14.10, p < .001, with a standardized effect size of d = -0.35. The fractional degrees of freedom are the signature of Welch's (1947) version of the t-test, which does not assume the two groups have equal variances and is the right default whenever they might differ. That second number deserves more attention than the first. An effect of 0.35 sits between the conventional small and medium benchmarks, which is to say the two groups still overlap a great deal, and knowing which kind of channel someone favors tells you something about whether they shout without telling you much."),
 ("Compare them on positive-word rate and the result is a near miss: 24.4 per thousand words against 18.7, t(99) = 1.20, which does not clear significance at any conventional threshold. Chapter 25 argues at length that this is not the same as showing the groups are identical. With 91 cases in the smaller group, a real difference of this size would frequently go undetected, and the correct conclusion is that the study did not settle the question rather than that there is nothing to settle.",
  "Compare them on positive-word rate and there is nothing: 20.7 per thousand words against 19.4, t(6383.20) = -1.27, p = .20, d = -0.03. Chapter 25 argues at length that a non-significant result is not proof the groups are identical, and that argument holds. But read this one with its sample size in hand, because the reading changes. On 91 cases you would conclude that the study could not settle the question. On 6,559 cases, with a standardized difference of three hundredths, the comparison had ample power to detect anything a reader would care about and detected nothing, so the defensible conclusion is that any real difference here is too small to matter. Same test, opposite readings, and what separates them is the power the design bought."),
]
for a, b in E:
    if a not in t:
        if b in t:
            continue
        sys.exit("NOT FOUND: %r" % a[:110])
    t = t.replace(a, b)
io.open(p, "w", encoding="utf-8", newline="\n").write(t)
print("patched chapter13")
